### ISSUE TITLE
API call not working for php7 for stage environment

### ISSUE THREAD

**Issue by mt15199** [click2mail/php-5.6andOver-Click2Mail-ClientSDK#1]
hello, I just tried downloading this SDK and hosted on my shared hosting site that used php7, I created an account in stage.click2mail.com. Tried scripts below but I couldn't make it work, both scripts below resulting into the same error, I tried simple mail call and the document create method, please see below for my directory structure and code snippet of scripts.
![dir](https://user-images.githubusercontent.com/31434956/39868574-cdf738fa-548c-11e8-8ea1-37c40e47f504.PNG)

SIMPLE MAIL CALL
```
<?PHP
require_once('c2mAPIRest.php');
$c2m = new c2mAPIRest("marlzdummy@gmail.com","Tambiga1!","stage"); //Change stage to live for production
$c2m->addAddress("John","Smith","MyCompany","1234 Test Street","Apt 2","Oak Brook","IL","60523","USA");
$file = './test.pdf';
$output = $c2m->runAll("Letter 8.5 x 11","Address on Separate Page","Next Day","#10 Double Window","Black and White","White 24#","Printing Both sides",$file,$c2m->createAddressList());
print_r($output);
echo "\n\n";
echo "documentId: ".$c2m->documentId."\n\n";
echo "AddressListId: ".$c2m->addressListId."\n\n";
echo "jobId: ".$c2m->jobId."\n\n";
$c2m->clearJob(); //call this before you create your next job;

?>
```

USE OF DOCUMENT CREATE METHOD

```
<?PHP
require_once('c2mAPIRest.php');
$c2m = new c2mAPIRest("marlzdummy@gmail.com","Tambiga1!","stage"); //Change stage to live for production
$file = './test.pdf';
$docClass = "Letter 8.5 x 11";
$c2m->document_create($file, $docClass);
echo "\n\n";
echo "documentId: ".$c2m->documentId."\n\n";
?>
```

ERROR

```
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; c2mAPIRest has a deprecated constructor in /home/u668303149/public_html/SDK_Click2Mail/c2mAPIRest.php on line 2

Warning: simplexml_load_string(): Entity: line 1: parser error : Opening and ending tag mismatch: HR line 1 and body in /home/u668303149/public_html/SDK_Click2Mail/c2mAPIRest.php on line 305

Warning: simplexml_load_string(): rect.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.70</h3></body> in /home/u668303149/public_html/SDK_Click2Mail/c2mAPIRest.php on line 305

Warning: simplexml_load_string(): ^ in /home/u668303149/public_html/SDK_Click2Mail/c2mAPIRest.php on line 305

Warning: simplexml_load_string(): Entity: line 1: parser error : Opening and ending tag mismatch: HR line 1 and html in /home/u668303149/public_html/SDK_Click2Mail/c2mAPIRest.php on line 305

Warning: simplexml_load_string(): u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.70</h3></body></html> in /home/u668303149/public_html/SDK_Click2Mail/c2mAPIRest.php on line 305

Warning: simplexml_load_string(): ^ in /home/u668303149/public_html/SDK_Click2Mail/c2mAPIRest.php on line 305

Warning: simplexml_load_string(): Entity: line 1: parser error : Premature end of data in tag body line 1 in /home/u668303149/public_html/SDK_Click2Mail/c2mAPIRest.php on line 305

Warning: simplexml_load_string(): u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.70</h3></body></html> in /home/u668303149/public_html/SDK_Click2Mail/c2mAPIRest.php on line 305

Warning: simplexml_load_string(): ^ in /home/u668303149/public_html/SDK_Click2Mail/c2mAPIRest.php on line 305

Warning: simplexml_load_string(): Entity: line 1: parser error : Premature end of data in tag html line 1 in /home/u668303149/public_html/SDK_Click2Mail/c2mAPIRest.php on line 305

Warning: simplexml_load_string(): u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.70</h3></body></html> in /home/u668303149/public_html/SDK_Click2Mail/c2mAPIRest.php on line 305

Warning: simplexml_load_string(): ^ in /home/u668303149/public_html/SDK_Click2Mail/c2mAPIRest.php on line 305
Error: Cannot create object
```

**Comment by Vinnie881** [comment]
From what I can see it looks like the call is not making it to the API.  Did you put the test.pdf in the same location you are running the php from?  I will give you some code to check a few things, but if you have google hangouts I can probably jump on a screen share with you and help you out as well?

**Comment by mt15199** [comment]
Hi Vince, thank you for your reply. Yes the test.pdf is on the same directory, please see it on attached image. I think I have google hangout, here's my email mt15199@gmail.com

**Comment by mt15199** [comment]
Hi Vincent, any update on this please? thanks

**Comment by Vinnie881** [comment]
Can you be on hangout around 1pm cst tomorrow?  My email is vsenese@npwu.com<mailto:vsenese@npwu.com>

We should be able to figure it out at that time.  Have you been able to make any curl calls from that machine?  Are we sure the hosting environment is not blocking outgoing requests?

Sent from my iPhone

On May 17, 2018, at 4:40 PM, mt15199 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Vincent, any update on this please? thanks

**Comment by Vinnie881** [comment]
I am able to duplicate issue.  I am working on now.  My php 5.6 environment and my php7 environment are both having the same issue as you. I believe this was tested prior, so I am not sure if something changed or why it is now throwing an error, but the document creation is not generating a documentId in php and that is causing the trickle down issue you are seeing.  I will post an update as soon as I have it fixed.

Thanks

**Comment by mt15199** [comment]
Hi Vincent, thank you for your update. Alright, looking forward for the fix.

**Comment by Vinnie881** [comment]
Ok, I got the fix working.  It appears explicitly defining the mime content type of the file to application/pdf during the document upload was causing a bad request, when previously it would not work without.  I will update the API, but I have to get an answer from Click2Mail on if the XML output is no longer going to be a default.

Are you on a time crunch, or will Monday work for you?

**Comment by mt15199** [comment]
Hi Vincent, no rush, Monday would work for me. Thanks again,

**Comment by Vinnie881** [comment]
Can you please confirm the new patch is working for you?

Thanks!

**Comment by mt15199** [comment]
Hi Vincent,
It does work now.

Thanks,

**Comment by Vinnie881** [comment]
Sounds good, I will close out issue.

Thanks!

**Comment by mt15199** [comment]
Alright, feel free to do so, thanks again! Have a nice day..
